### ISSUE TITLE
deparse can't handle 'ILIKE'

### ISSUE THREAD

**Issue by primeapple** [lfittl/pg_query#123]
Hi everyone,
just wanted to update you, that I found a problem in this wonderful application!

When trying to parse:
```sql
SELECT a FROM x WHERE a ILIKE '%test%'
```

The wrapper throws an Exception (this is with a different query, but also with ILIKE):

```
Traceback (most recent call last):
       14: from /usr/bin/irb:23:in `<main>'
       13: from /usr/bin/irb:23:in `load'
       12: from /usr/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       11: from (irb):3
       10: from (irb):3:in `rescue in irb_binding'
        9: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `deparse'
        8: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `map'
        7: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:7:in `block in deparse'
        6: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:18:in `from'
        5: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:130:in `deparse_item'
        4: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:200:in `deparse_raw_stmt'
        3: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:138:in `deparse_item'
        2: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:798:in `deparse_select'
        1: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:46:in `deparse_item'
RuntimeError (Can't deparse: A_Expr: {"kind"=>9, "name"=>[{"String"=>{"str"=>"~~*"}}], "lexpr"=>{"ColumnRef"=>{"fields"=>[{"String"=>{"str"=>"a"}}], "location"=>22}}, "rexpr"=>{"A_Const"=>{"val"=>{"String"=>{"str"=>"%test%"}}, "location"=>30}}, "location"=>24})
```

I would think this is kind of easy to fix, unfortunately I'm really bad with ruby, so I won't be able to help :(

greetings

**Comment by emin100** [comment]
Solved with #133
