### ISSUE TITLE
'nil'-Error when deparsing certain queries

### ISSUE THREAD

**Issue by primeapple** [lfittl/pg_query#124]
Also I found another bug:

When trying to deparse:
```sql
select array[]::text[] from x
```

I get an the following error:
```
Traceback (most recent call last):
       16: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `deparse'
       15: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:6:in `map'
       14: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:7:in `block in deparse'
       13: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:18:in `from'
       12: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:130:in `deparse_item'
       11: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:200:in `deparse_raw_stmt'
       10: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:138:in `deparse_item'
        9: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:784:in `deparse_select'
        8: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:784:in `map'
        7: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:785:in `block in deparse_select'
        6: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:134:in `deparse_item'
        5: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:297:in `deparse_restarget'
        4: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:148:in `deparse_item'
        3: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:923:in `deparse_typecast'
        2: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:55:in `deparse_item'
        1: from /home/user/.gem/ruby/2.6.0/gems/pg_query-1.1.0/lib/pg_query/deparse.rb:226:in `deparse_a_arrayexp'
NoMethodError (undefined method `map' for nil:NilClass)
```

I think this definitely is a bug and should be fixed because something is nil, that certainly shouldn't be null. (bad bad guy, dynamic typing in ruby :-) )

**Comment by lfittl** [comment]
This should be fixed by https://github.com/lfittl/pg_query/commit/823155cec95a7e720633b2f498581b92a18722fb
