### ISSUE TITLE
Exception when calling tables method

### ISSUE THREAD

**Issue by ankane** [lfittl/pg_query#69]
Hey @lfittl, thanks again for this awesome project.

Someone reported a query to me that throws an error with the `tables` method. Here's the simplest version that reproduces it.

```
PgQuery.parse("SELECT * FROM pg_catalog.pg_class c JOIN (SELECT 17650 AS oid UNION ALL SELECT 17663 AS oid) vals ON c.oid = vals.oid").tables
```

Backtrace

```
NoMethodError: undefined method `map' for nil:NilClass
	from /Users/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg_query-0.13.2/lib/pg_query/parse.rb:208:in `block in load_tables_and_aliases!'
	from /Users/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg_query-0.13.2/lib/pg_query/parse.rb:186:in `loop'
	from /Users/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg_query-0.13.2/lib/pg_query/parse.rb:186:in `load_tables_and_aliases!'
	from /Users/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg_query-0.13.2/lib/pg_query/parse.rb:59:in `tables_with_types'
	from /Users/andrew/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pg_query-0.13.2/lib/pg_query/parse.rb:33:in `tables'
	from (irb):14
	from /Users/andrew/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```

**Comment by lfittl** [comment]
@ankane Thanks for the report :)

Just fixed this in https://github.com/lfittl/pg_query/commit/c86323c4e3ef7fc36ac5d57ae2952d752de994f6 and released as `0.13.3` on Rubygems

**Comment by ankane** [comment]
Awesome, that was super quick. Thanks!

**Comment by ankane** [comment]
On a related note, very thankful for the `tables` method. It's super helpful, and very non-trivial from the code.
